# Generated by Django 3.1.1 on 2020-11-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
