# Generated by Django 3.1.1 on 2020-11-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_delete_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('CO', models.DecimalField(decimal_places=6, max_digits=10)),
                ('HC', models.DecimalField(decimal_places=6, max_digits=10)),
                ('NO', models.DecimalField(decimal_places=6, max_digits=10)),
                ('CO2', models.DecimalField(decimal_places=6, max_digits=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='data.city')),
            ],
        ),
    ]
