# Generated by Django 3.1.1 on 2020-11-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_powerplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
