# Generated by Django 3.1.1 on 2020-11-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_city_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
