# Generated by Django 3.1.1 on 2020-11-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='CO',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='NO2',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='O3_8',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='PM10',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='PM25',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='SO2',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='sensor_locatiion',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='wind_direction',
            field=models.CharField(default='N', max_length=3),
        ),
        migrations.AddField(
            model_name='city',
            name='wind_speed',
            field=models.IntegerField(default=0),
        ),
    ]
