# Generated by Django 3.1.1 on 2020-12-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20201109_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='PM25',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
